name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter_contrib_nbextensions=0.5.0
  - joblib=0.13.0
  - jupyter=1.0.0
  - keyring=17.0.0
  - matplotlib=3.0.2
  - pandas=0.23.4
  - pyodbc=4.0.25
  - python=3.7.1
  - scikit-learn=0.20.2
  - sqlalchemy=1.2.15
- pip:
    - lightgbm==2.2.2

